Add purge script
status-im/infra-role-gitea pull request #2
Opened 2023-11-22 14:14 UTC by apentori

linked to : 

* https://github.com/status-im/infra-ci/issues/121

Can be improve to set special depending on the name of the container if need be. In that case, it will need to read a custom yaml conf file.

2023-11-24 10:12 UTC, jakubgs requested changes

2023-11-24 10:12 UTC, jakubgs commented on defaults/main.yml
> +gitea_purge_max_retention: 15
If this purge is only for containers then the variables should include `container` in the name:
```suggestion
# Purge
gitea_container_purge_timer_name: 'gitea-purge-artifact'
gitea_container_purge_timer_user: '{{ gitea_app_host_uid }}'
gitea_container_purge_timer_frequency: 'daily'
gitea_container_purge_timer_timeout: 120
gitea_container_purge_max_retention: 15
```

2023-11-24 10:12 UTC, jakubgs commented on templates/purge-registry.py.j2
> +        username=environ.get('GITEA_PASSWORD')
Same as in the other init script. Just use `default` and `assert` in `parse_args()`.

2023-11-24 10:12 UTC, jakubgs commented on templates/purge-registry.py.j2
> +    return res
You are repeating yourself too much. This needs to be a `GiteaAPI` class that has thin-wrappers around `_request()`.

Like this:
https://github.com/status-im/infra-utils/blob/34e5d068a46c408426b7b6c4182f1ab828632528/ethereum/validator_check.py#L12-L34

2023-11-24 10:12 UTC, jakubgs commented on templates/purge-registry.py.j2
> +                        failed.append(err.response.text)
Try avoiding too many nesting indents. You can do that by inverting `if`s:
```suggestion
                if not cont.should_be_purge(retention):
                    continue
                try:
                    delete_artifact(url, basic, cont)
                 except requests.exceptions.HTTPError as err:
                    failed.append(err.response.text)
```

2023-11-24 10:12 UTC, jakubgs commented on templates/purge-registry.py.j2
> +        exit(1)
What is the point of this `try`/`except`? Why are you hiding an exception? Just let it bubble to the top and break.

2023-11-24 10:12 UTC, jakubgs commented on templates/purge-registry.py.j2
> +    retention=int(args.retention)
Just apply `type=int` to the `add_argument()` method.

2023-11-27 10:48 UTC, jakubgs commented
Some issues I saw:
```
  File "/docker/gitea/purge-registry.py", line 92
    parser.add_argument('-r', '--retention',  required=True,  type=int, help='Maximum retention period for each artifact in days', type=int)
                                                                                                                                   ^^^^^^^^
SyntaxError: keyword argument repeated: type
```
```
Traceback (most recent call last):
  File "/docker/gitea/purge-registry.py", line 124, in <module>
    main()
  File "/docker/gitea/purge-registry.py", line 104, in main
    giteaApi = GiteaApi('%s/api/v1' % args.url, args.username, args.password)
  File "/docker/gitea/purge-registry.py", line 42, in __init__
    self.auth = requests.auth.HTTPBasicAuth(args.username, args.password)
NameError: name 'args' is not defined
```
```
Traceback (most recent call last):
  File "/docker/gitea/purge-registry.py", line 124, in <module>
    main()
  File "/docker/gitea/purge-registry.py", line 105, in main
    orgs=get_organization(giteaApi)
  File "/docker/gitea/purge-registry.py", line 62, in get_organization
    res=giteaApi._get('orgs')
  File "/docker/gitea/purge-registry.py", line 53, in _get
    return self._req('GET', path)
  File "/docker/gitea/purge-registry.py", line 49, in _req
    logging.error(tval.text)
NameError: name 'tval' is not defined. Did you mean: 'rval'?
```
```
ERROR:root:Error 404 when trying to get the organization: Not found.
Traceback (most recent call last):
  File "/docker/gitea/purge-registry.py", line 124, in <module>
    main()
  File "/docker/gitea/purge-registry.py", line 107, in main
    for org in orgs:
TypeError: 'NoneType' object is not iterable
```

2023-11-27 12:54 UTC, apentori commented
Issues solved:

```
Nov 27 12:53:37 node-01.do-ams3.harbor.ci systemd[1]: Starting Timer to perform clean...
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Querrying all the organization
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Deployment : ['acid-info', 'nimbus', 'status', 'wakuorg']
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Get containers from acid-info
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Querrying org acid-info to list all artifacts
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:01:33.884066 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:01:42.884304 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:01:48.884376 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:01:54.884420 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/ui is 5 days, 4:01:58.884458 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:01:59.884495 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:02:18.884530 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/ui is 5 days, 4:02:18.884563 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:02:22.884596 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:02:36.884631 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/ui is 5 days, 4:02:41.884665 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:02:56.884698 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:02:58.884732 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/ui is 5 days, 4:03:05.884765 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:03:17.884803 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:03:27.884835 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/ui is 5 days, 4:03:34.884869 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:03:38.884903 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:04:00.884938 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/ui is 5 days, 4:04:01.884973 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:04:01.885006 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:04:24.885042 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/ui is 5 days, 4:04:24.885076 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:04:24.885103 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/ui is 5 days, 4:04:48.885128 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/relayer is 5 days, 4:04:48.885152 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact kurate/contracts is 5 days, 4:04:49.885176 old
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Get containers from nimbus
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Querrying org nimbus to list all artifacts
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Get containers from status
Nov 27 12:53:37 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Querrying org status to list all artifacts
Nov 27 12:53:38 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Get containers from wakuorg
Nov 27 12:53:38 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:Querrying org wakuorg to list all artifacts
Nov 27 12:53:38 node-01.do-ams3.harbor.ci purge-registry.py[2871158]: INFO:root:The artifact redis is 5 days, 4:02:22.104223 old
Nov 27 12:53:38 node-01.do-ams3.harbor.ci systemd[1]: gitea-purge-artifact.service: Deactivated successfully.
Nov 27 12:53:38 node-01.do-ams3.harbor.ci systemd[1]: Finished Timer to perform clean.
```

2023-11-28 09:04 UTC, jakubgs commented on tasks/purge-registry.yml
> +    systemd_timer_script_args: '--url http://localhost:{{ gitea_app_cont_web_port }}  --retention {{ gitea_purge_max_retention }}'
You can make this more readable using `>-`:
```suggestion
    systemd_timer_script_args: >-
      --url http://localhost:{{ gitea_app_cont_web_port }}
      --retention {{ gitea_purge_max_retention }}
```

2023-11-28 09:05 UTC, jakubgs approved these changes
Looks good.

2023-11-28 09:10 UTC, merged